default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: forecast_dev

test:
  <<: *default
  database: forecast_test

production:
  <<: *default
  url: forecast_prod
